# N-Get Development Configuration
# Overrides for development environment

# Logging optimized for development
logging:
  level: "debug"
  format: "text"
  enableColors: true
  outputs:
    - console

# Security relaxed for development
security:
  blockPrivateNetworks: false
  blockLocalhost: false
  rateLimiting:
    enabled: false
  ipv6:
    blockPrivateRanges: false
    blockDocumentation: false
    blockMulticast: false
    strictValidation: false
    
# Development features enabled
development:
  hotReload: true
  validateOnChange: true
  debugMode: true
  mockExternalServices: false

# AI features enabled for development
ai:
  enabled: true
  profiles:
    enabled: true
    learningEnabled: true

# Monitoring disabled in development
monitoring:
  enabled: false
  tracingEnabled: true
  performanceTracking: true

# Lower limits for development testing
downloads:
  maxConcurrent: 2
  chunkUpdateFrequency: 500

# Shorter timeouts for faster development feedback
http:
  timeout: 15000
  maxRetries: 2
  ipv6:
    enabled: true
    dualStack: true
    dnsResolution:
      timeout: 3000
      retries: 1